server:
  port: 8762
  
eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8761/eureka
     
spring:
  application:
    name: movie-zuul
    
zuul:
  ignored-services: '*'
  routes:
    movie-service:
      path: /movies/**
      service-id: movie-service         
        