spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cts_movie
    username: root
    password: akshat1996
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  pattern:
    console: "%d{dd-MM-YYYY HH:mm:ss} - %msg%n"
management:
  endpoints:
    web:
      exposure:
        include: refresh
